### ISSUE TITLE
04-03 - GET /practice?mode=api

### ISSUE THREAD

**Issue by Breadkenty** [Breadkenty/assignments#14]
## Objectives

- Create a simple API
- Practice problem solving

## Requirements

- Create 2 endpoints, `/mumbling` and `/explosion`, that are based off of the katas,`[https://www.codewars.com/kata/mumbling](https://www.codewars.com/kata/mumbling)` and `[https://www.codewars.com/kata/digits-explosion(https://www.codewars.com/kata/digits-explosion)` respectfully.

### Explorer Mode

- [x] Create a new `webapi` api project
- [x] Create a endpoint for the `mumbling` endpoint
  - [x] Create a new Controller called `MumblingController`
  - [x] This will have one `HttpGet` method
  - [x] The method will accept a string either as a URL parameter or a query parameter. Your choice.
  - [x] This endpoint method will take the string passed to it, manipulate according to the kata [https://www.codewars.com/kata/mumbling(https://www.codewars.com/kata/mumbling) and return the result
  - [x] Have your code return the string
- [x] Create a endpoint for the `explosion` endpoint
  - [x] Create a new Controller called `ExplosionController`
  - [x] This will have one `HttpGet` method
  - [x] The method will accept a string either as a URL parameter or a query parameter. Your choice.
  - [x] This endpoint method will take the string passed to it, manipulate according to the kata
        [https://www.codewars.com/kata/digits-explosion(https://www.codewars.com/kata/digits-explosion) and return the result
  - [x] Have your code return the string

## Adventure Mode

None

## Epic Mode

None

## Resources

- Use [Insomnia](https://insomnia.rest/) for interacting with your API.

**Comment by Breadkenty** [comment]
https://github.com/Breadkenty/04-03-get_practice_api

**Comment by gstark** [comment]
I don't see any controllers here? Are you missing a commit?

**Comment by Breadkenty** [comment]
Your homework **04-03 - GET /practice?mode=api** was marked: **Unacceptable**


![Lets try that again](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBGQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--971830e3dee5baf5a6262d5071fe0cf38b68ac61/3oAt2dA6LxMkRrGc0g.gif)
> &ldquo;Lets try that again&rdquo;

**Comment by Breadkenty** [comment]
https://github.com/Breadkenty/04-03-get_practice_api

**Comment by gstark** [comment]
Nice work with the exception capture!

**Comment by Breadkenty** [comment]
Your homework **04-03 - GET /practice?mode=api** was marked: **Meets Expectations**


![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBWZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--19d6199fa14f30b194db6d85ef06369fdd985597/giphy-10.gif)
> &ldquo;Well done!&rdquo;
