### ISSUE TITLE
07 - 05 - Calculating Hooks

### ISSUE THREAD

**Issue by Breadkenty** [Breadkenty/assignments#28]
Practice is key to gaining the mileage needed to conquer programming. A very common practice problem is to recreate a working calculator. A basic calculator is a good exercise in using state, effects, and components to create a powerful and robust UI.

## Objectives

- Practice using *functional components with hooks*
- Practice implementing a UI wire-frame

## Requirements

Create a simple calculator that allows the user to add, multiply, subtract, and divide two numbers. Here is a sample UI:

![Calculator](https://raw.githubusercontent.com/suncoast-devs/handbook/master/assignments/assets/calculator.png)

## Notes

- Take this in small steps just like we did in class. Start with the HTML, then CSS, then with basic functionality.

### Explorer Mode

- [x] Implement something similar to the example UI using HTML and CSS inside a React app
- [x] As a user, I should be able to add two numbers
- [x] As a user, I should be able to add subtract numbers
- [x] As a user, I should be able to add multiple numbers
- [x] As a user, I should be able to add divide numbers
- [x] The clear button should reset the current calculation

### Adventure Mode

- [x] Show the user their history in a list
- [x] Be able to chain together results. For example, the user should be able to input `2 + 3 - 4 + 5` and get the correct answer
- [x] Let the user use their keyboard in addition to the mouse

### Epic Mode

- [ ] Using your systems calculator app as inspiration, implement as many features as you can, including, but not limited to scientific mode, exponents, and the order of operations.

**Comment by Breadkenty** [comment]
This is far from perfect, and If I go into doing the order of operations I'm sure it's gonna take ANOTHER entire day. But this is what I have, it's not perfect but I'm pretty proud of some of the things I implemented in this one. Especially dealing with negative number input, % on an input, and delete a character on input. I'm gonna call it quits on this one, it was a loooooong day phew!
https://github.com/Breadkenty/07-05-calculating-hooks

**Comment by Breadkenty** [comment]
Your homework **08 - 01 - Calculating Hooks** was marked: **Exceeds Expectations**


![Celebrate ](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBEdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ac44f3b65ce52bd3753ea7c498abaacb9cb95e6f/tenor.gif)
> &ldquo;Celebrate &rdquo;

**Comment by gstark** [comment]
Goes to show how even simple looking things (like a calculator) can have intricate and deep logic to them. Sometimes simple looking things are complex and sometimes complex looking things are, well, simple.
