### ISSUE TITLE
Spit and Polish - 

### ISSUE THREAD

**Issue by Breadkenty** [Breadkenty/assignments#30]
Your GitHub repository will be part of your portfolio and you will likely link to it from your portfolio.

Creating a clean looking README is as important for a project as having nice clean code.

Here are some examples of great READMEs:

- https://github.com/axios/axios
- https://github.com/Microsoft/vscode
- https://github.com/twbs/bootstrap
- https://github.com/electron/electron

Here are some example of great student READMEs:

- https://github.com/cfsanderson/Minesweeper
- https://github.com/m1g/tic-react-toe
- https://github.com/m1g/snowman

## Objectives

- Create quality READMEs

### Explorer Mode

- [x] Choose several (at least three) repositories to update the READMEs
- [x] Include a description, in your own words, of what the assignment was
- [x] Include a list of technologies (and links to the homepage for each) you used
- [x] Include a link to the project in production (surge, etc.)
- [x] Include a screenshot or an animated gif (see [Kap](https://github.com/wulkano/kap), [Recordit](http://recordit.co/), or [Licecap](https://www.cockos.com/licecap/))
- Optional:
  - [x] Include an aspect you are particularly proud of
  - [x] Include a snippet of code you are proud of (see GitHub Markdown on how to format code snippets)

**Comment by Breadkenty** [comment]
https://github.com/Breadkenty/01-04-Blackjack
https://github.com/Breadkenty/03-03-Rhythms_Gonna_Get_You
https://github.com/Breadkenty/04-02-Pokemon_Client
https://github.com/Breadkenty/06-04-Roshambo
https://github.com/Breadkenty/07-02-Color_Picker
https://github.com/Breadkenty/04-04-The_Rise_of_the_Tamagotchi
https://github.com/Breadkenty/04-04-Rise_of_the_Tamagotchi_Console_App

I updated every single assignment's README with outlines of the homework and gifs on how to use every single console app just so they're not blank. However, I went into a few assignments and added more information along with screenshots and gifs showing how the app works. These are the ones that I went more in detail

**Comment by Breadkenty** [comment]
Also for the iteration assignments, I went ahead and pasted my solutions in the readme:
https://github.com/Breadkenty/02-02-C-Sharp_Iteration
https://github.com/Breadkenty/06-02-Iteration_in_Javascript-Epic_Mode
https://github.com/Breadkenty/06-02-Iteration_in_JavaScript-Explorer_Mode

**Comment by Breadkenty** [comment]
Your homework **Spit and Polish - ** was marked: **Meets Expectations**


![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBVUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--03a26be8c53c7287bc40570f4006121a970942ce/giphy-5.gif)
> &ldquo;Well done!&rdquo;

**Comment by gstark** [comment]
:+1:
