### ISSUE TITLE
02 - 03 - First Bank of Suncoast - 

### ISSUE THREAD

**Issue by Breadkenty** [Breadkenty/assignments#7]
For this assignment, you will be creating your own personal bank account manager. You will be creating an app that will let you track both a savings account and a checking account total by performing transactions, such as withdrawals, deposits, and transfers. The application will also save your information in a file so you can track your account totals over time.

## Objectives

- Practice control structures.
- Practice data structures.
- Practice working with user data.
- Practice with LINQ.
- Practice with OOP concepts.
- Practice working with files.

## Requirements

Create a console app that allows a user to manage a banking account.

As user should be able to make transactions against their accounts.

The transaction information should be stored in a file, using a `CSV`(or `JSON`) format to record the data.

Balances will be computed by determining the cumulative effect of all the transactions in order. For instance, if a user deposits 10 to their savings account and then withdraws 8 from their savings account, their balance is computed as 2.

### Explorer Mode

- [x] The app should load past transactions from a file at start up.
- [x] As a user I should be able to see the balances in my saving and checking account when the program first starts.
- [x] Never allow withdrawing or depositing more money than allowed. That is, we cannot allow our accounts to go negative.
- [x] When prompting for an amount to deposit or withdraw always ensure the amount is positive.
- [x] As a user I should be able to deposit funds to my savings account.
- [x] As a user I should be able to deposit funds to my checking account.
- [x] As a user I should be able to withdraw funds from my savings account.
- [x] As a user I should be able to withdraw funds from my checking account.
- [x] As a user I should be able to see my account balances.
- [x] The app should, after each transaction, write all the transactions to a file using a standard format.

### Adventure Mode

- [x] Add the ability to transfer funds from my checking account to my savings account.
- [x] Add the ability to transfer funds from my savings account to my checking accounts.
- [x] Add the ability to have multiple users. There are many steps to take here, so take the time to plan out the changes needed. This includes changes to the interface as well as changes to how you store the data.

### Epic Mode

- [x] Add simple password protection to your user's accounts

## Additional Resources

- .NET

  - [.NET Documentation](https://docs.microsoft.com/en-us/dotnet/)

  - [CsvHelper](https://joshclose.github.io/CsvHelper/getting-started)

**Comment by Breadkenty** [comment]
https://github.com/Breadkenty/02-03-FirstBankOfSuncoast

I did not get to complete this assignment but this is what I have. I pretty much have everything but getting the files to save correctly where the account information and the user information can't be saved together. I didn't mean to do adventure mode but I planned for the ability to have multiple users from the beginning.

**Comment by Breadkenty** [comment]
Your homework **02 - 03 - First Bank of Suncoast - ** was marked: **Needs Improvement**

![Keep rolling with it](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBHZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1a5861defaf25697d82b847afc71ef4a7637666f/chihuaha.gif)
> &ldquo;Keep rolling with it&rdquo;
__&mdash; via **[Katherine Trammell](https://gifs.suncoast.io/venerations/16)**__

**Comment by gstark** [comment]
This is great and I would accept it. However, we should be keeping a `List<Transaction>` as part of the account, not just a balance.

See if you can finish both of those aspects.

**Comment by Breadkenty** [comment]
https://github.com/Breadkenty/02-03-FirstBankOfSuncoast

Implemented the Transaction feature. To make up for multiple accounts storing as a file, I instead made temporary instances where a user can log into various accounts. However, the user is not related to the transactions that are loaded to the project.

I need to sleep...

**Comment by Breadkenty** [comment]
Your homework **02 - 03 - First Bank of Suncoast - ** was marked: **Meets Expectations**


![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBVUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--03a26be8c53c7287bc40570f4006121a970942ce/giphy-5.gif)
> &ldquo;Well done!&rdquo;
